In [36]:
from zipfile import ZipFile
import os
import pandas as pd

os.chdir("../")

In [37]:
country = "Spain"
month = 11
year = 2019
election_type = "general"

In [38]:
output = []
path = f"data/{country}/{year}{month}.zip"
for i in ZipFile(path).namelist():
    print(i)
    if i[-3:] == "DAT":
        tmp = pd.read_csv(ZipFile(path).open("09021911.DAT"), error_bad_lines=False, header=None, encoding="latin-1")
        output.append(tmp)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Spain/201911.zip'

In [ ]:
pd.read_csv(ZipFile(path).open("04021911.DAT"), error_bad_lines=False, header=None, encoding="latin-1")

C:\Users\cnava\AppData\Local\Temp\ipykernel_42144\2089367733.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  pd.read_csv(ZipFile(path).open("04021911.DAT"), error_bad_lines=False, header=None, encoding="latin-1")

                                                      0
0     022019111179999000031003TLaia                 ...
1     022019111179999000031004TEduard               ...
2     022019111179999000031005TXènia                ...
3     022019111179999000031006TDavid                ...
4     022019111179999000040001TAndrés               ...
...                                                 ...
4467  022019111439999000096005TJaume                ...
4468  022019111439999000096006TAdrià                ...
4469  022019111439999000101001TRut                  ...
4470  022019111439999000101002TGerard               ...
4471  022019111439999000101003TRafael               ...

[4472 rows x 1 columns]

In [ ]:
[(1, 2, "election_type"), (3, 6, "year"), (7, 8, "month"), (9, 9, "n_round"),
(10, 11, "region_id"), (12, 13, "province_id"), (14, 16, "commune_id"), (17, 18, "district_commune_id"),
(19, 22, "section_id"), (23, 23, "polling_code"), (24, 30, "ine_census"), (31, 37, "census_cera"), (38, 44, "census_cere"),
(45, 51, "total_cere"), (52, 58, "voters_first"), (59, 65, "voters_second"), (66, 72, "blank_votes"), (73, 79, "null_votes"),
(80, 86, "votes"), (87, 93, "favour_votes"), (94, 100, "negative_votes"), (101, 101, "official_data")]

[(1, 2, 'election_type'),
 (3, 6, 'year'),
 (7, 8, 'month'),
 (9, 9, 'n_round'),
 (10, 11, 'region_id'),
 (12, 13, 'province_id'),
 (14, 16, 'commune_id'),
 (17, 18, 'district_commune_id'),
 (19, 22, 'section_id'),
 (23, 23, 'polling_code'),
 (24, 30, 'ine_census'),
 (31, 37, 'census_cera'),
 (38, 44, 'census_cere'),
 (45, 51, 'total_cere'),
 (52, 58, 'voters_first'),
 (59, 65, 'voters_second'),
 (66, 72, 'blank_votes'),
 (73, 79, 'null_votes'),
 (80, 86, 'votes'),
 (87, 93, 'favour_votes'),
 (94, 100, 'negative_votes'),
 (101, 101, 'official_data')]

In [ ]:
pd.read_csv(ZipFile(path).open("09021911.DAT"), header=None)

                                                       0
0      022019111010400302001 B00004460000446000000000...
1      022019111010400602001 A00008420000842000000000...
2      022019111010400604001 B00004540000454000000000...
3      022019111010401303008 U00006620000662000000000...
4      022019111010401304006 U00006660000666000000000...
...                                                  ...
59622  022019111195200107002 B00005280000528000000000...
59623  022019111195200107003 B00006190000619000000000...
59624  022019111195200107006 A00006150000615000000000...
59625  022019111195200107006 B00006990000699000000000...
59626  022019111195200108009 B00008150000815000000000...

[59627 rows x 1 columns]

In [ ]:
df = pd.concat(output, ignore_index=True)

In [ ]:
columns = [(1, 2, "election_type"), (3, 6, "year"), (7, 8, "month"), (9, 9, "n_round"),
(10, 11, "state_id"), (12, 13, "province_id"), (14, 16, "commune_id"), (17, 18, "district_commune_id"),
(19, 22, "section_id"), (23, 23, "polling_code"), (24, 29, "candidate_id"), (30, 36, "value")]

df = pd.read_csv(ZipFile(path).open("10021911.DAT"), header=None)

for column in columns:
    df[column[2]] = df[0].str[column[0] - 1:column[1]]
    
df["polling_id"] = df["state_id"] + df["province_id"] + df["commune_id"] + df["district_commune_id"] + df["section_id"] + df["polling_code"]
df[["candidate_id", "value"]] = df[["candidate_id", "value"]].astype(int)
df.head()

,0,election_type,year,month,n_round,state_id,province_id,commune_id,district_commune_id,section_id,polling_code,candidate_id,value,polling_id
0,022019111010400101001 B0000980000000,02,2019,11,1,01,04,001,01,001,B,98,0,010400101001 B
1,022019111010400201001 B0000980000000,02,2019,11,1,01,04,002,01,001,B,98,0,010400201001 B
2,022019111010400301001 U0000580000000,02,2019,11,1,01,04,003,01,001,U,58,0,010400301001 U
3,022019111010400301002 A0000090000002,02,2019,11,1,01,04,003,01,002,A,9,2,010400301002 A
4,022019111010400301003 A0000090000000,02,2019,11,1,01,04,003,01,003,A,9,0,010400301003 A

In [ ]:
columns = [(1, 2, "election_type"), (3, 6, "year"), (7, 8, "month"), (9, 14, "candidate_id"),
(15, 64, "candidate"), (65, 214, "candidate_description"), (215, 220, "candidate_code_province"), 
(221, 226, "candidate_code_state"), (227, 232, "candidate_code_country")]

df_candidates = pd.read_csv(ZipFile(path).open("03021911.DAT"), encoding="latin-1", header=None)

for column in columns:
    df_candidates[column[2]] = df_candidates[0].str[column[0] - 1:column[1]]

df_candidates[["candidate_id"]] = df_candidates[["candidate_id"]].astype(int)
df_candidates["candidate"] = df_candidates["candidate"].str.strip()
df_candidates["candidate_description"] = df_candidates["candidate_description"].str.strip()

df_candidates.head()

,0,election_type,year,month,candidate_id,candidate,candidate_description,candidate_code_province,candidate_code_state,candidate_code_country
0,02201911000002AHORA CANARIAS ...,02,2019,11,2,AHORA CANARIAS,AHORA CANARIAS: Alternativa Nacionalista Canar...,000002,000002,000002
1,02201911000003ANDECHA ...,02,2019,11,3,ANDECHA,ANDECHA ASTUR,000003,000003,000003
2,02201911000005AUNACV ...,02,2019,11,5,AUNACV,AUNA COMUNITAT VALENCIANA,000005,000005,000005
3,02201911000006AVANT ADELANTE LOS VERDES ...,02,2019,11,6,AVANT ADELANTE LOS VERDES,AVANT ADELANTE LOS VERDES,000006,000006,000006
4,02201911000007AVANT ADELANTE LOS VERDES ...,02,2019,11,7,AVANT ADELANTE LOS VERDES,LOS VERDES ECOPACIFISTAS ADELANTE,000007,000006,000006

In [39]:
df_candidates[["candidate_id", "candidate"]].tail(50)

     candidate_id                 candidate
56             63                      PCTC
57             64                      PCTE
58             65                 PCTE/ELAK
59             66                 PCTE/ELAK
60             67                      PCTG
61             68                     PDSJE
62             72                        PH
63             73                     P-LIB
64             74                PODEMOS-EU
65             75              PODEMOS-EUIB
66             76              PODEMOS-EUPV
67             77                PODEMOS-IU
68             78                PODEMOS-IU
69             79               PODEMOS-IU-
70             80       PODEMOS-IU-BATZARRE
71             81          PODEMOS-IU LV CA
72             82                PODEMOS-IX
73             83                        PP
74             84                        PP
75             85                        PP
76             86                   PP-FORO
77             87                      PPSO
78             88                       PRC
79             89                    PREPAL
80             90                  PSC-PSOE
81             91                PSdeG-PSOE
82             92             PSE-EE (PSOE)
83             93                      PSOE
84             94                      PSOE
85             95                     PUM+J
86             96                     PUM+J
87             97                     PUM+J
88             98                     PUM+J
89             99                     PUM+J
90            100                      PYLN
91            101          RECORTES CERO-GV
92            102  RECORTES CERO-GV-PCAS-TC
93            103                      RISA
94            105                 SOLIDARIA
95            106               SOMOS REGIÓ
96            108               ¡TERUEL EXI
97            109                       UDT
98            110            UIG-SOM-CUIDES
99            111               UNIDOS SÍ-A
100           112               UNIÓN REGIO
101           113                       UPL
102           114                    VERDES
103           115                LOS VERDES
104           116                       VOX
105           117                       XAV

In [ ]:
df = pd.merge(df, df_candidates[["candidate_id", "candidate"]], on="candidate_id")
df["state_id"] = df["state_id"].astype(int)
df.head()

,0,election_type,year,month,n_round,state_id,province_id,commune_id,district_commune_id,section_id,polling_code,candidate_id,value,polling_id,candidate_x,candidate_y
0,022019111010400101001 B0000980000000,02,2019,11,1,1,04,001,01,001,B,98,0,010400101001 B,PUM+J ...,PUM+J
1,022019111010400201001 B0000980000000,02,2019,11,1,1,04,002,01,001,B,98,0,010400201001 B,PUM+J ...,PUM+J
2,022019111010400303003 C0000980000000,02,2019,11,1,1,04,003,03,003,C,98,0,010400303003 C,PUM+J ...,PUM+J
3,022019111010400602001 A0000980000000,02,2019,11,1,1,04,006,02,001,A,98,0,010400602001 A,PUM+J ...,PUM+J
4,022019111010401101002 A0000980000000,02,2019,11,1,1,04,011,01,002,A,98,0,010401101002 A,PUM+J ...,PUM+J

In [ ]:
df.state_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 15, 16, 17, 18, 19, 99,  9,
       11, 13, 14])

In [ ]:
df_filtered = df[["candidate", "value", "polling_id"]].copy()
df_filtered["rank"] = df_filtered.groupby(["polling_id"])["value"].rank("min", ascending=False).astype(int)

KeyError: "['candidate'] not in index"

In [ ]:
df.candidate.unique()

array(['PUM+J                                             ',
       'PCPA                                              ',
       'AxSÍ                                              ',
       'PACMA                                             ',
       'VOX                                               ',
       'RECORTES CERO-GV                                  ',
       'Cs                                                ',
       'PODEMOS-IU LV CA                                  ',
       'EB                                                ',
       'PSOE                                              ',
       'PP                                                ',
       'PCOE                                              ',
       'MÁS PAÍS-AN                                       ',
       'PCTE                                              ',
       'IZAR                                              ',
       'CAnda                                             ',
       'RISA                                              ',
       'PYLN                                              ',
       'PCPE                                              ',
       'FIA                                               ',
       'CHA                                               ',
       'PODEMOS-IU-                                       ',
       'AUNACV                                            ',
       'PODEMOS-IU                                        ',
       '¡TERUEL EXI                                       ',
       'UDT                                               ',
       'M PAÍS-CHA-                                       ',
       'MAS                                               ',
       'PP-FORO                                           ',
       'PH                                                ',
       'MÁS PAÍS-EQ                                       ',
       'PODEMOS-IX                                        ',
       'ANDECHA                                           ',
       'PODEMOS-EUIB                                      ',
       'MÉS-ESQUERR                                       ',
       'M PAÍS                                            ',
       'P-LIB                                             ',
       'CONTIGO                                           ',
       'PDSJE                                             ',
       'AHORA CANARIAS                                    ',
       'VERDES                                            ',
       'PCPC                                              ',
       'NC-CCa-PNC                                        ',
       'CCa-PNC-NC                                        ',
       'PRC                                               ',
       'RECORTES CERO-GV-PCAS-TC                          ',
       'FE de las J                                       ',
       'XAV                                               ',
       'PREPAL                                            ',
       'UPL                                               ',
       'centrados                                         ',
       'PPSO                                              ',
       'UNIÓN REGIO                                       ',
       'MÁS PAÍS                                          ',
       'IZQP                                              ',
       'JxCAT-JUNTS                                       ',
       'ECP-GUANYEM                                       ',
       'PCTC                                              ',
       'PSC-PSOE                                          ',
       'CUP-PR                                            ',
       'I.Fem                                             ',
       'ERC-SOBIRANISTES                                  ',
       'EXTREMADURA UNIDA                                 ',
       'PCTG                                              ',
       'PODEMOS-EU                                        ',
       'BNG                                               ',
       'PSdeG-PSOE                                        ',
       'C 21                                              ',
       'NA+                                               ',
       'PCTE/ELAK                                         ',
       'GBAI                                              ',
       'EH Bildu                                          ',
       'PODEMOS-IU-BATZARRE                               ',
       'EAJ-PNV                                           ',
       'PSE-EE (PSOE)                                     ',
       'ELAK/PCTE                                         ',
       'SOLIDARIA                                         ',
       'MÁS PAÍS-CA                                       ',
       'DPL                                               ',
       'SOMOS REGIÓ                                       ',
       'MÉS COMPROM                                       ',
       'ERPV                                              ',
       'PODEMOS-EUPV                                      ',
       'AVANT ADELANTE LOS VERDES                         ',
       'AVANT LOS VERDES                                  ',
       'UIG-SOM-CUIDES                                    ',
       'UNIDOS SÍ-A                                       ',
       'MDyC                                              ',
       'LOS VERDES                                        ',
       'CpM                                               '], dtype=object)

In [ ]:
df_filtered = df_filtered.groupby(["polling_id", "candidate"]).agg({"value": "sum"})
df_filtered["rate"] = df_filtered.groupby(level=[0], group_keys=False).apply(lambda x: x/x.sum())
df_filtered = df_filtered.reset_index()
df_filtered = df_filtered[["polling_id", "candidate", "rate", "value"]]

In [ ]:
df_nuts = pd.read_csv("data/Spain/nuts_2_equivalences.csv")
df_nuts["nuts_1"] = df_nuts["nuts_2"].str[0:3]
df_nuts.head()

   state_id nuts_2 province_name nuts_1
0         1   ES61     Andalucía    ES6
1         2   ES24        Aragón    ES2
2         3   ES12      Asturias    ES1
3         4   ES53      Baleares    ES5
4         5   ES70      Canarias    ES7

In [ ]:
df_filtered.to_csv(f"data_output/Spain/{year}_{election_type}.csv.gz", compression="gzip", index=False)

In [ ]:
df_location = df[["polling_id", "state_id", "province_id", "commune_id", "district_commune_id"]]
df_location = pd.merge(df_location, df_nuts, how="left", on="state_id")
df_location.to_csv(f"data_output/Spain/{year}_{election_type}_location.csv.gz", compression="gzip", index=False)